### ISSUE TITLE
ValueError: could not convert string to float: '295 722'

### ISSUE THREAD

**Issue by thebruuu** [cybermaggedon/ixbrl-parse#2]
Hi
I got a conversion error using the file from https://www.renaultgroup.com/finance/information-reglementee/
https://www.renaultgroup.com/wp-content/uploads/2022/03/969500f7jltx36oui695-2021-12-31-2.zip

**Comment by cybermaggedon** [comment]
Thanks for the report, I'm taking a look.

**Comment by cybermaggedon** [comment]
A couple of iXBRL transform mods, that test file works for me now.  Thanks for the report!

**Comment by cybermaggedon** [comment]
The fix is in PyPI package 0.9.4
https://pypi.org/project/ixbrl-parse/0.9.4/
